### PR TITLE
Updated characters data.

### PR DESCRIPTION
**Pull request by Ido-Barnea**

### CODE REVIEW

**Review by KostaSav — CHANGES_REQUESTED** [review]
@Ido-Barnea 
Can you please review your changes or post some sources?
For example, I could not find anything about Neville's eyes being black or Madam Pomfrey's hair and eyes being brown.
Thanks! 😃

**Comment by Ido-Barnea** [comment]
> @Ido-Barnea Can you please review your changes or post some sources? For example, I could not find anything about Neville's eyes being black or Madam Pomfrey's hair and eyes being brown. Thanks! 😃

I didn't realize I had to keep track of my sources, so I don't have them. For what it's worth, I remember making sure they are valid. It's fine if you don't want to merge because of that, but I don't have any sources to send you. Sorry.

**Comment by KostaSav** [comment]
You don't "have to keep track of your sources". You can search and post her when you find them, so that we make sure all merged info is accurate.
Or you can remove the dubious/inaccurate fields and do a new pull request with the verified ones, for the moment.

**Comment by KostaSav** [comment]
Closing this pull request as there was no action for a month.

**Pull request closed without merging**
