### PR TITLE
Add UUID to each characters, removed duplicates entries of Dedalus Di…

### PR DESCRIPTION
**Pull request by NigelGee**
Add UUID to each character and removed duplicates entries of Dedalus Diggle, Rodolphus Lestrange and Emmeline Vance, also change data in yearOfBirth and length to alway be String

### CODE REVIEW

**Comment by KostaSav** [comment]
@NigelGee can you please make a separate pull request for each type of change? Removal of duplicate entries I can probably merge right away, but the other two changes need some more review with @bethfraser .

**Comment by NigelGee** [comment]
Okay will do. I found the duplicates when adding the UUIDs which I removed then. If you search the names I put these are the duplicates.

Regards
Nigel Gee

**Comment by NigelGee** [comment]
I have made a pull request now with only the duplicates characters.

I was looking at the other changes. Some other the fields have a mixed type eg Number and String

yearOfBirth
wand.length

This make these field useless to access. Which would be preferable, make those number to Strings or keep them as numbers and remove the strings field from other characters (this would be my choice) but the former is easier.

Looking forward to hearing from you.

Regards

Nigel

**Comment by KostaSav** [comment]
About the initial issues you mentioned:

> 1. keep `yearOfBirth` and `wand.length` as numbers and remove the strings field from other characters

I agree that this choice would be best. What would be the default value for the fields that don't contain a value? 0?


> 2. Add UUID to each characters

This seems useful. Is it just a random UUID for each object? How was the same UUID generated for the duplicates that you found? I am not sure how this field would be populated, in case of future character additions.

**Pull request closed without merging**
